name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  CONTAINER_REGISTRY: kitscontainer.azurecr.io
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
  EDGE_DEVICE_1_ID: microservice-edge-device-1
  EDGE_DEVICE_1_HOSTNAME: microservice-edge-device-1-hostname
  EDGE_DEVICE_1_SAS_TOKEN: ${{ secrets.EDGE_DEVICE_1_SAS_TOKEN }}
  EDGE_DEVICE_2_ID: microservice-edge-device-2
  EDGE_DEVICE_2_HOSTNAME: microservice-edge-device-2-hostname
  EDGE_DEVICE_2_SAS_TOKEN: ${{ secrets.EDGE_DEVICE_2_SAS_TOKEN }}
  EDGE_DEVICE_3_ID: microservice-edge-device-3-id
  EDGE_DEVICE_3_HOSTNAME: microservice-edge-device-3-hostname
  EDGE_DEVICE_3_SAS_TOKEN: ${{ secrets.EDGE_DEVICE_3_SAS_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Build and push Temperature Data Collector Microservice
        uses: docker/build-push-action@v2
        with:
          context: ./Temperature Data Collector Microservice
          push: true
          tags: ${{ github.sha }}
          registry: ${{ env.CONTAINER_REGISTRY }}
          repository: temperature-data-collector

      - name: Build and push Graph Generator Microservice
        uses: docker/build-push-action@v2
        with:
          context: ./Graph Generator Microservice
          push: true
          tags: ${{ github.sha }}
          registry: ${{ env.CONTAINER_REGISTRY }}
          repository: graph-generator

      - name: Build and push GUI Microservice
        uses: docker/build-push-action@v2
        with:
          context: ./GUI Microservice
          push: true
          tags: ${{ github.sha }}
          registry: ${{ env.CONTAINER_REGISTRY }}
          repository: gui

      - name: Deploy Temperature Data Collector Microservice
        run: |
          az extension add --name azure-iot
          az iot edge deployment update --hub-name IOT-microservice --content deployment-temperature-data-collector.json --target-condition "deviceId='microservice-edge-device-1'"

      - name: Deploy Graph Generator Microservice
        run: |
          az extension add --name azure-iot
          az iot edge deployment update --hub-name IOT-microservice --content deployment-graph-generator.json --target-condition "deviceId='microservice-edge-device-2'"

      - name: Deploy GUI Microservice
        run: |
          az extension add --name azure-iot
          az iot edge deployment update --hub-name IOT-microservice --content deployment-gui.json --target-condition "deviceId='microservice-edge-device-3'"
